
[nfs]
172.31.39.240 ansible_ssh_user='ec2-user'

[webservers]
172.31.37.141 ansible_ssh_user='ec2-user'
172.31.40.1 ansible_ssh_user='ec2-user'

[db]
 172.31.39.231 ansible_ssh_user='ec2-user' 

[lb]
172.31.42.207  ansible_ssh_user='ubuntu'